# Generated by Django 4.2.23 on 2025-10-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBmP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='user_transactions',
        ),
    ]
