# Generated by Django 4.2.23 on 2025-10-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OBmP', '0003_alter_transaction_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(blank=True, db_column='recipient_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='OBmP.newaccount'),
        ),
    ]
